version: '3.8'

services:
  # VeritabanÄ±
  db:
    image: postgres:13
    container_name: securechat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 
      POSTGRES_DB: securechat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend API
  api:
    build: .
    container_name: securechat_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: securechat
      DB_PORT: 5432
      JWT_SECRET: securechatteam19
      PORT: 3000
    depends_on:
      - db

volumes:
  pgdata: